name: 'Change Log'

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  update_release_draft:
    permissions:
      # write permission is required to update the release draft
      contents: write
      # PR write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
